### PR TITLE
Fixing DB mapping issue in Create Event

### LINKED ISSUE #1496: Issue in "Create Event"
When attempting to create an event into th event calendar , after entering the event details the system is not saving the data.

Steps to reproduce the issue

1. click on the Events from features list in the home screen
2. click on the "create Event"
3. here create an event by clicking on a date
4. click the save button lastly

### PR DESCRIPTION
**Pull request by musaibasrar**
closes #1496

### CODE REVIEW

File: src/main/java/org/ideoholic/curium/model/event/dto/Event.java [hunk 1]
```diff
@@ -1,155 +1,60 @@
...
     
-    @Column(nullable = false)
+    @Column(name = "end_date_time", nullable = false)
     private LocalDateTime endDateTime;
     
-    @Column
+    @Column(name = "location")
     private String location;
     
     @Column
```
Comment (reehanlalkhan) [inline src/main/java/org/ideoholic/curium/model/event/dto/Event.java]:
```suggestion
    @Column(name = "color")
```

**Review by reehanlalkhan — CHANGES_REQUESTED** [review]

**Review by reehanlalkhan — APPROVED** [review]
