### PR TITLE
Exam Mark entry Issue Resolved

### LINKED ISSUE #1490: Exam Mark entry Issue
When attempting to enter the marks of an exam then the page is not showing the students data of searched class (eg class 1).

Steps to reproduce the issue

1. Click on the home button from header shortcut
2. click on the exams from features list
3. here select a class from click the search button

### LINKED ISSUE #1546: Unable to enter marks of a student
When attempting to marks of any student, the system fails to save the marks of any student . Instead, an error is displayed, as shown in the attached screenshot.

Steps to Reproduce

On the Home Screen, click enter marks inside exam in left admin.
enter marks page will be displayed.
enter name or class and click search
after clicking fill Exam Class, Subject, Exam, Academic Year
After filling these enter marks obtained in the input box of table
and click add button below in place of adding marks it will error page

Expected Result
Marks should be added for the selected student.

Actual Result
It is giving an error page.

Attachments
Screenshot of the error (attached below)

Image

Fixed as part of: [1490](https://github.com/musaibasrar/Curium/issues/1490)

### PR DESCRIPTION
**Pull request by musaibasrar**
closes #1490

### CODE REVIEW

File: src/main/java/org/ideoholic/curium/model/marksdetails/service/MarksDetailsService.java [hunk 1]
```diff
@@ -423,18 +424,22 @@ public MarksResponseDto viewMarks(MarksViewDto dto, String branchId) {
...
 		for (Parents parents : searchStudentList) {
-
 			List<Marks> singleMarksDetails = marksDetailsDao.readListOfMarks(parents.getStudent().getSid(),subjectDetailsId,Integer.parseInt(examIdName[0]));
-			for (Marks marks : singleMarksDetails) {
-				int subSubjectId = marks.getSubsubjectid();
-				if ( subSubjectId ==0) {
-					newStudentList.add(parents);
-					newMarksDetails.add(marks);
-					log.debug("Marks Details: {}", marks.getMarksobtained());
+			if(CollectionUtils.isEmpty(singleMarksDetails)) {
```
Comment (reehanlalkhan) [inline src/main/java/org/ideoholic/curium/model/marksdetails/service/MarksDetailsService.java]:
```suggestion
			if(!CollectionUtils.isEmpty(singleMarksDetails)) {
```

**Review by reehanlalkhan — CHANGES_REQUESTED** [review]

File: src/main/java/org/ideoholic/curium/model/marksdetails/service/MarksDetailsService.java [hunk 2]
```diff
@@ -423,18 +424,22 @@ public MarksResponseDto viewMarks(MarksViewDto dto, String branchId) {
 
 		String[] examIdName = exam.split(":");
 		Subject subjectDetails = subjectDetailsDao.readSubjectByExam(Integer.parseInt(branchId), addClass, examIdName[1], Integer.parseInt(subject));
-		int subjectDetailsId = subjectDetails.getSubid();
-		List<Parents> newStudentList = new ArrayList<Parents>();
-		List<Marks> newMarksDetails = new ArrayList<Marks>();
+		int subjectDetailsId = 0;
+		if(subjectDetails != null) subjectDetails.getSubid();
```
Comment (reehanlalkhan) [inline src/main/java/org/ideoholic/curium/model/marksdetails/service/MarksDetailsService.java]:
```suggestion
		if(subjectDetails != null) subjectDetailsId = subjectDetails.getSubid();
```

**Review by reehanlalkhan — CHANGES_REQUESTED** [review]

**Review by reehanlalkhan — APPROVED** [review]
